// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: async (url, options) => {
        const res = await fetch(url, options);
        if (res.status === 401) {
          if (typeof window !== "undefined") {
            const keysToRemove: string[] = [];
            for (let i = 0; i < localStorage.length; i++) {
              const key = localStorage.key(i);
              if (key && (key.startsWith("sb-") || key.includes("supabase.auth.token"))) {
                keysToRemove.push(key);
              }
            }
            if (keysToRemove.length > 0) {
              keysToRemove.forEach((k) => localStorage.removeItem(k));
            }

            // Asynchronously sign out of in-memory auth state
            setTimeout(() => {
              if (_supabase) {
                _supabase.auth.signOut().catch(() => {});
              }
            }, 0);

            // Clean headers and retry as guest
            if (options) {
              const newOptions = { ...options };
              if (newOptions.headers) {
                if (newOptions.headers instanceof Headers) {
                  const clonedHeaders = new Headers(newOptions.headers);
                  clonedHeaders.delete("authorization");
                  if (!clonedHeaders.has("apikey")) {
                    clonedHeaders.set("apikey", SUPABASE_PUBLISHABLE_KEY);
                  }
                  newOptions.headers = clonedHeaders;
                } else if (Array.isArray(newOptions.headers)) {
                  newOptions.headers = newOptions.headers.filter(
                    ([h]) => h.toLowerCase() !== "authorization"
                  );
                } else if (typeof newOptions.headers === "object") {
                  const cleanedHeaders = { ...newOptions.headers } as Record<string, string>;
                  for (const key of Object.keys(cleanedHeaders)) {
                    if (key.toLowerCase() === "authorization") {
                      delete cleanedHeaders[key];
                    }
                  }
                  if (!cleanedHeaders.apikey && !cleanedHeaders.ApiKey) {
                    cleanedHeaders["apikey"] = SUPABASE_PUBLISHABLE_KEY;
                  }
                  newOptions.headers = cleanedHeaders;
                }
              }
              const retryRes = await fetch(url, newOptions);
              if (retryRes.ok) {
                return retryRes;
              }
            }
          }
        }
        return res;
      },
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
